# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-22 18:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policy_prototype', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coverage',
            name='policy',
        ),
        migrations.AddField(
            model_name='coverage',
            name='policy',
            field=models.ManyToManyField(related_name='coverages', to='policy_prototype.Policy'),
        ),
    ]
