# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-22 18:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('policy_prototype', '0002_auto_20170922_1839'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coverage',
            name='policy',
        ),
        migrations.AddField(
            model_name='coverage',
            name='policy',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='coverages', to='policy_prototype.Policy'),
            preserve_default=False,
        ),
    ]
